[theme]

backgroundColor = "#f4f1ec"
secondaryBackgroundColor = "#e0e4e7"
primaryColor = "#BF0603"
textColor = "#001524"
font = "sans serif"


[client]
toolbarMode = "viewer"


# [server]
# port = 8010
# enableCORS = false
# enableXsrfProtection = false
